apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
  # The access modes are:
  # ReadWriteOnce – the volume can be mounted as read-write by a single node
  # ReadOnlyMany – the volume can be mounted read-only by many nodes
  # ReadWriteMany – the volume can be mounted as read-write by many nodes
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
